# Generated by Django 4.2.5 on 2023-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(blank=True, to="theatre.actor"),
        ),
        migrations.AddField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(blank=True, to="theatre.genre"),
        ),
    ]
